package middleware

import (
	"crypto/subtle"
	"net/http"
	"strings"
)

const accessTokenCookie = "xcontrol_access_token"

// AccessToken protects the desktop backend with the per-process secret
// generated by Electron. An empty token keeps the developer web workflow
// available without authentication.
func AccessToken(token string, next http.Handler) http.Handler {
	if token == "" {
		return next
	}

	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if publicWithoutToken(r) || tokenMatches(r, token) {
			next.ServeHTTP(w, r)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		w.Header().Set("Cache-Control", "no-store")
		w.WriteHeader(http.StatusUnauthorized)
		_, _ = w.Write([]byte(`{"error":{"code":"UNAUTHORIZED","message":"invalid desktop access token"}}`))
	})
}

func publicWithoutToken(r *http.Request) bool {
	if r.Method == http.MethodGet && r.URL.Path == "/api/health" {
		return true
	}
	return r.Method == http.MethodGet &&
		strings.HasPrefix(r.URL.Path, "/api/sync/oauth/") &&
		strings.HasSuffix(r.URL.Path, "/callback")
}

func tokenMatches(r *http.Request, expected string) bool {
	token := ""
	if auth := r.Header.Get("Authorization"); strings.HasPrefix(auth, "Bearer ") {
		token = strings.TrimPrefix(auth, "Bearer ")
	} else if cookie, err := r.Cookie(accessTokenCookie); err == nil {
		token = cookie.Value
	}
	return subtle.ConstantTimeCompare([]byte(token), []byte(expected)) == 1
}
